name: Oh_the_dungeons_youll_go
authors: [shadow_wind,atomicstryker,greymerk,jaredbgreat,yeregorix,zhehe]
main: otd.Main
load: startup
api-version: 1.14
version: 7.0
commands:
  oh_the_dungeons:
    aliases: [otd]
    description: Open the OTD world manager
    usage: /<command>
  oh_the_dungeons_place:
    aliases: [otd_place]
    description: Place a dungeon at your current location
    usage: /<command> type
  oh_the_dungeons_cp:
    aliases: [otd_cp]
    description: Copy world config
    usage: /<command> source dest
permissions:
  oh_the_dungeons.admin:
    default: op
    description: open the inventory GUI
